name: braintree_payment
description: Flutter plugin that wraps the native Braintree SDKs. PayPal and Venmo.
version: 1.0.0
homepage: "https://github.com/yairsts/braintree_payment"

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.braintree.payment
        pluginClass: BraintreePaymentPlugin
      ios:
        pluginClass: BraintreePaymentPlugin
